{{- if .Values.preJob.preInitDB.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-db
  annotations:
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
{{ include "service.labels.standard" . | indent 4 }}
spec:
  backoffLimit: 1
  activeDeadlineSeconds: {{ .Values.preJob.timeout | default 300 }}
  template:
    metadata:
      name: {{ .Release.Name }}-init-db
    spec:
      initContainers:
      - command:
        - sh
        - -c
        - cp -rfp /var/mogu/* /tools
        image: {{ .Values.preJob.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: tools
        volumeMounts:
        - mountPath: /tools
          name: tools-jar
      containers:
      - name: {{ .Release.Name }}-init-db
        image: {{ include "service.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /bin/sh
        - -c
        - >
          java -Ddata.init=true
          -Dspring.datasource.url="{{ .Values.preJob.preInitDB.datasource.url }}"
          -Dspring.datasource.username={{ .Values.preJob.preInitDB.datasource.username }}
          -Dspring.datasource.password={{ .Values.preJob.preInitDB.datasource.password }}
          -Dspring.datasource.driver-class-name={{ .Values.preJob.preInitDB.datasource.driver }}
          -Dinstaller.jarPath=/app.jar
          -Dlogging.level.root=info
          -Dinstaller.mapping=script/db/service-mapping.xml
          -jar /var/mogu/mogu-tool-liquibase.jar;
        volumeMounts:
        - mountPath: /var/mogu
          name: tools-jar
      {{- if .Values.image.private }}
      imagePullSecrets:
        - name: {{.Values.image.imagePullSecrets}}
      {{end}}
      restartPolicy: Never
      volumes:
      - emptyDir: {}
        name: tools-jar
{{- end }}