# Default values for nacos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # mode: quickstart
  mode: standalone
  #mode: cluster
  storageClass:
    provisioner:
  #nfs
  # provisioner: fuseim.pri/ifs
  ###ceph
  #  provisioner: ceph.com/rbd

############################mysql###########################
mysql:
  rootPassword: password
  database: nacos
  user: nacos
  password: nacos
  port: 3306

######nfs
#    archiveOnDelete: "false"

######ceph
#    monitors: 10.144.131.48:6789
#    adminId: admin
#    adminSecretName: ceph-secret-admin
#    adminSecretNamespace: nacos
#    pool: nacos-mysql-data
#    userId: mysql
#    userSecretName: ceph-secret-mysql
#    userSecretNamespace: nacos
#    fsType: ext4
#    imageFormat: "2"
#    imageFeatures: "layering"





############################mysql###########################

############################nacos###########################
replicaCount: 1

image:
  repository: nacos/nacos-server
  tag: latest
  pullPolicy: IfNotPresent

health:
  enabled: false

env:
  domainName: cluster.local
  preferhostmode: hostname
  serverPort: 8848
  dbHost: mysql

persistence:
  enabled: false
  storageClassName:
  classParameters: {}
  data:
    accessModes:
      - ReadWriteOnce
    storageClassName:
    resources:
      requests:
        storage: 1Gi
  plugin:
    accessModes:
      - ReadWriteOnce
    storageClassName:
    resources:
      requests:
        storage: 1Gi
  log:
    accessModes:
      - ReadWriteOnce
    storageClassName:
    resources:
      requests:
        storage: 1Gi

service:
  type: ClusterIP
  #  type: NodePort
  port: 8848
  #  nodePort: 30000
  rpcPort: 7848


ingress:
  enabled: false
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: nacos.local.com
      paths: /

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 500m
#    memory: 2Gi
annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}



