# Default values for minio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: ""

image:
  repository: minio/minio
  tag: latest
  pullPolicy: IfNotPresent

env:
  MINIO_ACCESS_KEY: minio
  MINIO_SECRET_KEY: minio123


strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0

## Minio Master Liveness Probe
livenessProbe:
  enabled: false
  # initialDelaySeconds: 30
  # periodSeconds: 10
  # timeoutSeconds: 5
  # successThreshold: 1
  # failureThreshold: 5

## Minio Master Readiness Probe
readinessProbe:
  enabled: false
#   initialDelaySeconds: 5
#   periodSeconds: 10
#   timeoutSeconds: 1
#   successThreshold: 1
#   failureThreshold: 5

service:
  name: minio
  enabled: true
  type: ClusterIP
  port: 9000

  # externalIPs:
  # - 192.168.12.175

## Security context
securityContext:
  enabled: true
  runAsUser: 999
  fsGroup: 999


metrics:
  group: minio
  path: /
logs:
  enabled: false
  parser: docker


resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 2Gi
  requests:
    # cpu: 100m
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  stoargeCalss:
  # subPath:
  accessMode: ReadWriteOnce
  size: 1Gi


## Ingress 相关配置
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  # nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
  path: /
  host: minio.local.com
  tls: []
  # - secretName: minio-example-tls
  #   hosts:
  #   - minio.mogu.local.com
