{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "service.labels.standard" . | nindent 4 }}
  annotations:
{{ toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if not (empty .Values.service.externalIPs) }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | nindent 4 }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
  {{- end }}
  selector:
{{ include "service.labels.standard" . | nindent 4 }}
{{- end }}
